<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * OfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferRepository extends \Doctrine\ORM\EntityRepository
{
        public function getUserOffers($id,$slug){
            $rsm = new ResultSetMappingBuilder($this->getEntityManager());
            $rsm->addRootEntityFromClassMetadata('AppBundle\Entity\Offer', 'o');

            $sql = "SELECT o.id,o.value, o.product_id,o.buyer_id,o.date,o.accept
                    FROM offer as o,product as p , user as u
                    WHERE p.id=o.product_id AND p.offerType= :offertype
                    AND  p.seller_id= :seller" ;
            $query = $this->_em->createNativeQuery($sql, $rsm);
            $query->setParameter('offertype',$slug);
            $query->setParameter('seller',$id);
            return $query->getResult();

        }

        public function getUserOffersForAdmin($id){
            $rsm = new ResultSetMappingBuilder($this->getEntityManager());
            $rsm->addRootEntityFromClassMetadata('AppBundle\Entity\Offer', 'o');

            $sql = "SELECT o.id,o.value, o.product_id,o.buyer_id,o.date,o.accept
                    FROM offer as o,product as p , user as u
                    WHERE p.id=o.product_id  AND  p.seller_id= :seller" ;
            $query = $this->_em->createNativeQuery($sql, $rsm);
            $query->setParameter('seller',$id);
            return $query->getResult();
        }

}
