admin:
    resource: "@AdminBundle/Resources/config/routing.yml"



user:
    type: rest
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /api


App:
    type : rest
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /api

