# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:

        steg_serveur_utilisateurbundle:
            id: snap_sell_user_provider

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        info_user:
            pattern: ^/api/users/salt/*
            security: false
        salt_user:
            pattern: ^/admin/users/salt/*
            security: false

        near_product:
            pattern:  ^/api/nearproducts/*
            security: false

        login:
            pattern:  ^/admin/login
            security: false
        register:
            pattern:  ^/api/register
            security: false
        wsse_secured:
            pattern:   ^/api/*
            stateless: true
            wsse:      true
