<?php

namespace AdminBundle\Repository;

/**
 * DraftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DraftRepository extends \Doctrine\ORM\EntityRepository
{
}
